# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - gosec
    - errcheck
    - gocritic
    - prealloc
    - revive

issues:
  max-same-issues: 50
