#!/usr/bin/env bash
# Create systemd drop-in so stock haproxy.service uses easy-waf generated config.
# Idempotent. Run as root.
# Env: EASY_WAF_STATE_DIR, EASY_WAF_REPO_ROOT (for bootstrap + easy-waf-admin), EASY_WAF_ENV_FILE
set -euo pipefail

log() { echo "[easy-waf-haproxy-dropin] $*"; }

STATE_DIR="${EASY_WAF_STATE_DIR:-/var/lib/easy-waf}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${EASY_WAF_REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
CFG="${STATE_DIR}/haproxy/haproxy.cfg"
BOOT_SRC="${REPO_ROOT}/configs/defaults/haproxy-bootstrap.cfg"

if [[ "$(id -u)" != "0" ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

mkdir -p "${STATE_DIR}/haproxy" "${STATE_DIR}/revisions" "${STATE_DIR}/certs"
chown -R easy-waf:easy-waf "${STATE_DIR}" 2>/dev/null || true
chmod 0750 "${STATE_DIR}" "${STATE_DIR}/haproxy" "${STATE_DIR}/certs" "${STATE_DIR}/revisions" 2>/dev/null || true

if id haproxy &>/dev/null && ! id -nG haproxy | grep -qw easy-waf; then
  usermod -aG easy-waf haproxy
  log "Added haproxy to group easy-waf (read config + certs)"
fi
if id easy-waf &>/dev/null && id haproxy &>/dev/null && ! id -nG easy-waf | grep -qw haproxy; then
  usermod -aG haproxy easy-waf
  log "Added easy-waf to group haproxy (stats socket)"
fi

if [[ ! -s "$CFG" ]]; then
  if [[ -f "$BOOT_SRC" ]]; then
    sed "s|__EASY_WAF_STATE__|${STATE_DIR}|g" "$BOOT_SRC" >"${CFG}.tmp"
    install -m 0640 -o easy-waf -g easy-waf "${CFG}.tmp" "$CFG"
    rm -f "${CFG}.tmp"
    log "installed bootstrap $CFG"
  else
    log "WARNING: $CFG missing or empty and no bootstrap at $BOOT_SRC — run Apply from UI first"
  fi
else
  :
fi

DROPIN_DIR="/etc/systemd/system/haproxy.service.d"
DROPIN_FILE="${DROPIN_DIR}/easy-waf.conf"
mkdir -p "$DROPIN_DIR"
rm -f "${DROPIN_DIR}/50-easy-waf.conf" 2>/dev/null || true
cat >"$DROPIN_FILE" <<EOF
# Easy Home WAF — HAProxy uses generated config from easy-waf-api.
# Regenerated by scripts/fix-haproxy-easy-waf-dropin.sh
# RuntimeDirectory=/run/haproxy (systemd); + lines run as root (User=haproxy in stock unit).
# stats socket: /run/haproxy/easy-waf-admin.sock (see metrics.StatsSocketPath legacy migration).
[Service]
RuntimeDirectory=haproxy
RuntimeDirectoryMode=0755
ExecStartPre=
ExecStartPre=+/bin/rm -f /run/haproxy/easy-waf-admin.sock
ExecStartPre=/usr/sbin/haproxy -f ${CFG} -c
ExecStart=
ExecStart=/usr/sbin/haproxy -Ws -f ${CFG} -p /run/haproxy.pid
ExecReload=
ExecReload=+/bin/rm -f /run/haproxy/easy-waf-admin.sock
ExecReload=/usr/sbin/haproxy -f ${CFG} -c
ExecReload=/bin/kill -USR2 \$MAINPID
EOF
chmod 0644 "$DROPIN_FILE"
log "Created ${DROPIN_FILE}"

mkdir -p /run/haproxy
chown haproxy:haproxy /run/haproxy 2>/dev/null || true
chmod 0755 /run/haproxy 2>/dev/null || true
if [[ ! -f /etc/tmpfiles.d/easy-waf-haproxy.conf ]]; then
  cat >/etc/tmpfiles.d/easy-waf-haproxy.conf <<'EOF'
# easy-waf: HAProxy stats socket directory (systemd-tmpfiles)
d /run/haproxy 0755 haproxy haproxy -
EOF
  log "Created /etc/tmpfiles.d/easy-waf-haproxy.conf"
fi

if command -v aa-status &>/dev/null; then
  aa-status --enabled 2>/dev/null | head -5 || true
  log "AppArmor status captured (Ubuntu default for HAProxy)"
fi

systemctl daemon-reload
log "systemd daemon-reload done"

ENVF="${EASY_WAF_ENV_FILE:-/etc/easy-waf/easy-waf.env}"
ADMIN=""
for cand in /usr/sbin/easy-waf-admin /usr/bin/easy-waf-admin "${REPO_ROOT}/dist/easy-waf-admin"; do
  if [[ -x "$cand" ]]; then
    ADMIN="$cand"
    break
  fi
done
if [[ -n "$ADMIN" ]]; then
  set +e
  # Do not reload HAProxy mid-script (unit may be broken); this script restarts after haproxy -c.
  ae_out="$(EASY_WAF_SKIP_RELOAD=1 "$ADMIN" apply-edge -env-file "$ENVF" -state-dir "$STATE_DIR" 2>&1)"
  ae_ec=$?
  set -e
  if [[ $ae_ec -eq 0 ]]; then
    log "$ae_out"
  else
    log "WARNING: apply-edge failed (exit $ae_ec); install easy-waf-admin or Apply from UI"
    echo "$ae_out" >&2
  fi
else
  log "WARNING: easy-waf-admin not found — Apply from UI to refresh haproxy.cfg"
fi

if [[ ! -s "$CFG" ]]; then
  log "WARNING: $CFG still missing — skip haproxy -c and restart"
  log "Done. Next: Apply from UI, then: sudo systemctl restart haproxy"
  exit 0
fi

if ! /usr/sbin/haproxy -c -f "$CFG" 2>&1; then
  log "ERROR: haproxy -c -f $CFG failed"
  exit 1
fi

if systemctl cat haproxy.service >/dev/null 2>&1; then
  if systemctl restart haproxy.service; then
    log "haproxy.service restarted"
  else
    log "ERROR: haproxy restart failed — journalctl -u haproxy -n 80 --no-pager"
    exit 1
  fi
else
  log "WARNING: haproxy.service not found"
fi

log "Done."
